language: node_js
node_js:
  - "11"
services:
  - postgresql
before_install:
  - cd src
  - npm i -g sequelize-cli
  - npm i -g nodemon
install:
  - npm i --save-dev
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - npm test