language: node_js
node_js:
  - "11"
services:
  - postgresql
  - redis-server
env:
  - PORT=3000 DB_NAME=test DB_TEST=test JWT_SECRET=tHl5is5eCr3t JWT_EXPIRESIN=3600000
before_install:
  - cd src
  - npm i -g sequelize-cli
  - npm i -g nodemon
install:
  - npm i --save-dev
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - npm test
