version: '3'
services:
  postgres:
    image: postgres
    container_name: restapi_postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
