version: '3'
services:
  postgres:
    image: postgres
    container_name: unisquare_postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
  redis:
    image: redis
    container_name: unisquare_redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/data/redis:/data
